// account
export const ACCOUNT_LOGIN_LOADING = 'ACCOUNT_LOGIN_LOADING';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_ERROR = 'ACCOUNT_LOGIN_ERROR';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';


// courses
export const COURSES_FETCH = 'COURSES_FETCH';
export const COURSES_FETCH_LOADING = 'COURSES_FETCH_LOADING';
export const COURSES_FETCH_SUCCESS = 'COURSES_FETCH_SUCCESS';
export const COURSES_FETCH_ERROR = 'COURSES_FETCH_ERROR';
export const COURSES_SELECT = 'COURSES_SELECT';

// lecture
export const LECTURE_LOADING = 'LECTURE_LOADING';
export const LECTURE_LOAD_SUCCESS = 'LECTURE_LOAD_SUCCESS';
export const LECTURE_LOAD_FAILURE = 'LECTURE_LOAD_FAILURE';
export const LECTURE_DOWNLOAD_START = 'LECTURE_DOWNLOAD_START';
export const LECTURE_DOWNLOAD_PROGRESS = 'LECTURE_DOWNLOAD_PROGRESS';
export const LECTURE_DOWNLOAD_END = 'LECTURE_DOWNLOAD_END';
export const LECTURE_CLEAR = 'LECTURE_CLEAR';
export const LECTURE_CLEAR_SUCCESS = 'LECTURE_CLEAR_SUCCESS';
export const LECTURE_CLEAR_FAILURE = 'LECTURE_CLEAR_FAILURE';
// layout
export const PLAYER_ACTIVATE = 'PLAYER_ACTIVATE';
export const PLAYER_RESIZE = 'PLAYER_RESIZE';
export const SCREENSHOT_RESIZE = 'SCREENSHOT_RESIZE';
export const PLAYER_CHANGE_SCREEN_RATIO = 'PLAYER_CHANGE_SCREEN_RATIO';
export const PLAYER_RELAYOUT = 'PLAYER_RELAYOUT';
export const PLAYER_TIMEUPDATE = 'PLAYER_TIMEUPDATE';
// screenshot
export const SCREENSHOT_TIMEUPDATE_LOCAL = 'SCREENSHOT_TIMEUPDATE_LOCAL';
export const SCREENSHOT_TIMEUPDATE_ONLINE = 'SCREENSHOT_TIMEUPDATE_ONLINE';
export const SCREENSHOT_DOWNLOADING = 'SCREENSHOT_DOWNLOADING';
export const SCREENSHOT_DOWNLOAD_SUCCESS = 'SCREENSHOT_DOWNLOAD_SUCCESS';
export const SCREENSHOT_DOWNLOAD_FAILURE = 'SCREENSHOT_DOWNLOAD_FAILURE';
export const SCREENSHOT_PREDOWNLOAD_SUCCESS = 'SCREENSHOT_PREDOWNLOAD_SUCCESS';
export const SCREENSHOT_DRAWING = 'SCREENSHOT_DRAWING';
export const SCREENSHOT_DRAW_SUCCESS = 'SCREENSHOT_DRAW_SUCCESS';
export const SCREENSHOT_DRAW_FAILURE = 'SCREENSHOT_DRAW_FAILURE';

// player
export const PLAYER_LOADSTART = 'PLAYER_LOADSTART';
export const PLAYER_CANPLAY = 'PLAYER_CANPLAY';
export const PLAYER_CANPLAYTHROUGH = 'PLAYER_CANPLAYTHROUGH';
export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PLAYING = 'PLAYER_PLAYING';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_MUTE = 'PLAYER_MUTE';
export const PLAYER_AUTOPAUSE = 'PLAYER_AUTOPAUSE';
export const PLAYER_FIRSTPLAY = 'PLAYER_FIRSTPLAY';
export const PLAYER_RATECHANGE = 'PLAYER_RATECHANGE';
export const PLAYER_VOLUMECHANGE = 'PLAYER_VOLUMECHANGE';
export const PLAYER_DURATIONCHANGE = 'PLAYER_DURATIONCHANGE';
export const PLAYER_PROGRESSCHANGE = 'PLAYER_PROGRESSCHANGE';
export const PLAYER_END = 'PLAYER_END';
export const PLAYER_WAITING = 'PLAYER_WAITING';
export const PLAYER_SEEKING = 'PLAYER_SEEKING';
export const PLAYER_SEEKED = 'PLAYER_SEEKED';
export const PLAYER_FULLSCREENCHANGE = 'PLAYER_FULLSCREENCHANGE';
export const PLAYER_ORIENTATION = 'PLAYER_ORIENTATION';
export const PLAYER_EXIT = 'PLAYER_EXIT';


// whiteboard
export const WHITEBOARD_TIMEUPDATE = 'WHITEBOARD_TIMEUPDATE';
export const WHITEBOARD_DRAW_SUCCESS = 'WHITEBOARD_DRAW_SUCCESS';
